
const API='https://grabmail.io/api/v1',KEY='hawa_mail_address_v5';let address='',messages=[],current=null,timer=null,auto=true,notify=false,save=true,loading=false;
const $=x=>document.getElementById(x), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(x){$('toast').textContent=x;$('toast').classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('on'),1800)}
function status(x,c=''){$('status').textContent=x;$('status').className='status '+c}
function randomName(){let a='abcdefghjkmnpqrstuvwxyz23456789',s='';for(let i=0;i<10;i++)s+=a[Math.floor(Math.random()*a.length)];return s}
function code(text){let m=String(text||'').match(/(?:^|[^0-9])([0-9]{4,8})(?![0-9])/);return m?m[1]:''}
function dt(x){try{return new Date(x).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'})}catch{return x||''}}
async function clip(x){try{await navigator.clipboard.writeText(x)}catch{let t=document.createElement('textarea');t.value=x;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast('تم النسخ')}
async function api(url,opt={}){let r=await fetch(url,{...opt,headers:{Accept:'application/json',...(opt.headers||{})}}),d=null;try{d=await r.json()}catch{}if(!r.ok){let e=new Error(d?.message||'تعذر الاتصال بالخدمة');e.status=r.status;throw e}return d}
async function create(){address=randomName()+'@grabmail.io';$('address').value=address;messages=[];render();if(save)localStorage.setItem(KEY,address);toast('تم إنشاء بريد جديد');await refresh(true)}
async function refresh(silent=false){if(!address||loading)return;loading=true;if(!silent)status('جاري التحديث…');try{let old=new Set(messages.map(x=>x.id)),d=await api(API+'/mailbox?address='+encodeURIComponent(address)+'&limit=200');messages=Array.isArray(d.messages)?d.messages:[];render();let fresh=messages.filter(x=>!old.has(x.id));if(fresh.length&&old.size){toast('وصلت '+fresh.length+' رسالة');if(notify&&'Notification'in window&&Notification.permission==='granted')new Notification('Hawa Mail',{body:fresh[0].subject||'رسالة جديدة'})}status('آخر تحديث: '+new Date().toLocaleTimeString('ar-EG'),'ok')}catch(e){status(e.status===429?'تم الوصول لحد الطلبات، انتظر قليلًا':'تعذر الاتصال بالخدمة','err');if(!silent)toast(e.message)}finally{loading=false}}
function render(){let q=$('search').value.toLowerCase().trim(),a=messages.filter(x=>((x.from||'')+' '+(x.subject||'')).toLowerCase().includes(q));$('count').textContent=messages.length;$('navCount').textContent=messages.length?' '+messages.length:'';if(!a.length){$('list').innerHTML='<div class="empty"><b>'+(messages.length?'لا توجد نتائج':'صندوق الوارد فارغ')+'</b><span>'+(messages.length?'جرّب بحثًا آخر.':'عند وصول رسالة ستظهر هنا تلقائيًا.')+'</span></div>';return}$('list').innerHTML=a.map(m=>`<button class="msg" data-id="${esc(m.id)}"><span class="avatar">${esc((m.from||'?').trim().charAt(0).toUpperCase())}</span><span><b>${esc(m.subject||'(بدون عنوان)')}</b><span class="sub">${esc(m.from||'مرسل غير معروف')}</span></span><span class="date">${esc(dt(m.date))}</span></button>`).join('');document.querySelectorAll('.msg').forEach(x=>x.onclick=()=>open(x.dataset.id))}
async function open(id){let meta=messages.find(x=>x.id===id);if(!meta)return;current=meta;$('subject').textContent=meta.subject||'(بدون عنوان)';$('meta').textContent='من: '+(meta.from||'—')+' • '+dt(meta.date);$('body').textContent='جاري تحميل الرسالة…';$('codebox').innerHTML='';$('modal').classList.add('on');try{let m=await api(API+'/message/'+encodeURIComponent(id)+'?mailbox='+encodeURIComponent(address));current={...meta,...m};let c=code((m.text||'')+' '+(m.subject||''));$('codebox').innerHTML=c?`<div class="code"><b>${esc(c)}</b><button class="copy" id="cc">نسخ</button></div>`:'';$('body').textContent=m.text||'لا يوجد محتوى نصي.';if($('cc'))$('cc').onclick=()=>clip(c)}catch(e){$('body').textContent=e.message}}
async function del(){if(!current)return;try{await api(API+'/message/'+encodeURIComponent(current.id)+'?mailbox='+encodeURIComponent(address),{method:'DELETE'});messages=messages.filter(x=>x.id!==current.id);$('modal').classList.remove('on');render();toast('تم حذف الرسالة')}catch(e){toast(e.message)}}
async function delAll(){for(const m of [...messages]){try{await api(API+'/message/'+encodeURIComponent(m.id)+'?mailbox='+encodeURIComponent(address),{method:'DELETE'})}catch{}}messages=[];render();toast('تم حذف الرسائل')}
function autoStart(){clearInterval(timer);if(auto)timer=setInterval(()=>refresh(true),1000)}
$('copy').onclick=()=>clip(address);$('newMail').onclick=create;$('refresh').onclick=()=>refresh();$('ref2').onclick=()=>refresh();$('delAll').onclick=delAll;$('search').oninput=render;$('close').onclick=()=>$('modal').classList.remove('on');$('del').onclick=del;$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('on')};$('copyCode').onclick=()=>current&&clip(code((current.text||'')+' '+(current.subject||'')));
$('genOtp').onclick=()=>{let x=String(Math.floor(100000+Math.random()*900000));$('otp').textContent=x;clip(x)};$('genPass').onclick=()=>{let a='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%',x='';for(let i=0;i<18;i++)x+=a[Math.floor(Math.random()*a.length)];$('pass').textContent=x;clip(x)};$('clear').onclick=()=>{localStorage.removeItem(KEY);create()};
$('auto').onclick=()=>{auto=!auto;$('auto').classList.toggle('on',auto);autoStart()};$('save').onclick=()=>{save=!save;$('save').classList.toggle('on',save);if(save&&address)localStorage.setItem(KEY,address);else localStorage.removeItem(KEY)};$('notify').onclick=async()=>{notify=!notify;$('notify').classList.toggle('on',notify);if(notify&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission()};$('lang').onclick=()=>toast('العربية مفعلة — English قريبًا');
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-go]').forEach(x=>x.classList.remove('active'));b.classList.add('active');let n=b.dataset.go;if(n==='settings'){$('settings').style.display='block';$('xo').style.display='none';$('settings').scrollIntoView({behavior:'smooth'})}else if(n==='xo'){$('settings').style.display='none';$('xo').style.display='block';$('xo').scrollIntoView({behavior:'smooth'})}else{$('settings').style.display='none';$('xo').style.display='block';if(n==='new')$('new').scrollIntoView({behavior:'smooth'});else if(n==='inbox')$('inbox').scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})}});
(async()=>{let s=localStorage.getItem(KEY);if(s){address=s;$('address').value=s;await refresh(true)}else await create();autoStart()})();

// Hawa XO: player X vs computer O
let xoBoard=Array(9).fill(''),xoGame=true;const XO_KEY='hawa_xo_scores_v1';let xoScore=JSON.parse(localStorage.getItem(XO_KEY)||'{"w":0,"d":0,"l":0}');function xoPaint(){xoBoard.forEach((v,i)=>{const b=document.querySelector(`.xo-cell[data-i="${i}"]`);b.textContent=v;b.className='xo-cell '+(v==='X'?'xo-x':v==='O'?'xo-o':'');b.disabled=!!v||!xoGame});$('xoWin').textContent=xoScore.w;$('xoDraw').textContent=xoScore.d;$('xoLoss').textContent=xoScore.l}function xoWinner(b){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'D':''}function xoMove(i){if(!xoGame||xoBoard[i])return;xoBoard[i]='X';let r=xoWinner(xoBoard);if(r)return xoEnd(r);xoGame=false;xoPaint();$('xoStatus').textContent='الكمبيوتر يفكر…';setTimeout(xoComputer,260)}function xoComputer(){if(!xoGame)return;let best=-Infinity,move=-1;function mm(b,depth,maximizing){const r=xoWinner(b);if(r==='O')return 10-depth;if(r==='X')return depth-10;if(r==='D')return 0;let val=maximizing?-Infinity:Infinity;for(let i=0;i<9;i++)if(!b[i]){b[i]=maximizing?'O':'X';const s=mm(b,depth+1,!maximizing);b[i]='';val=maximizing?Math.max(val,s):Math.min(val,s)}return val}for(let i=0;i<9;i++)if(!xoBoard[i]){xoBoard[i]='O';let s=mm(xoBoard,0,false);xoBoard[i]='';if(s>best){best=s;move=i}}if(move>=0)xoBoard[move]='O';let r=xoWinner(xoBoard);if(r)xoEnd(r);else{xoGame=true;$('xoStatus').textContent='دورك الآن';xoPaint()}}function xoEnd(r){xoGame=false;if(r==='X'){xoScore.w++;$('xoStatus').textContent='🎉 كسبت!'}else if(r==='O'){xoScore.l++;$('xoStatus').textContent='🤖 الكمبيوتر كسب'}else{xoScore.d++;$('xoStatus').textContent='🤝 تعادل'}localStorage.setItem(XO_KEY,JSON.stringify(xoScore));xoPaint()}function xoNew() {xoBoard=Array(9).fill('');xoGame=true;$('xoStatus').textContent='دورك الآن';xoPaint()}document.querySelectorAll('.xo-cell').forEach(b=>b.onclick=()=>xoMove(+b.dataset.i));$('xoReset').onclick=xoNew;$('xo').style.display='none';xoPaint();
window.addEventListener('load',()=>setTimeout(()=>{const l=$('loadingScreen');l.style.opacity='0';l.style.visibility='hidden';setTimeout(()=>l.remove(),500)},650));
